services:
  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=productsapi
      - MYSQL_ROOT_PASSWORD=pase14792
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pase14792
    ports:
      - "14792:3306"
    networks:
      main:
        aliases:
          - mysql-dev
    volumes:
      - mysqlDocker:/var/lib/mysql
  productsapi:
    image: productsapi:1.0.0
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql-dev:14792/productsapi?createDatabaseIfNotExist=true
      DB_USER_NAME: root
      DB_PASSWORD: pase14792
    ports:
      - 8080:8080
    networks:
      main:
        aliases:
          - productsapi-back
networks:
  main:
volumes:
  mysqlDocker:
    external:
      name: mysqlDocker